name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install requirements
      run: pip install -r requirements.txt
    
    - name: Run Ruff linter
      run: ruff check .
    
    - name: Run Ruff formatter check
      run: ruff format --check .

    - name: Build grpc files
      run: cd src && python -m grpc_tools.protoc --python_out=. --pyi_out=. --grpc_python_out=. app/proto/chat.proto --proto_path=.

    - name: Run unittests for server and client
      run: PYTHONPATH=$(pwd)/src python -m unittest tests/test_grpc.py